### ISSUE TITLE
[오픈소스 사용]

### ISSUE THREAD

**Issue by popop098** [samsunghappytree123/makead#10]
## 디스코드 정보를 기재해주세요.
+ 디스코드 닉네임#태그 (Discord#0000) : 가위(디코접음)#8844, gawi#9537
+ 디스코드 ID (123456789) : 300535826088067072, 281566165699002379

## 오픈소스를 사용하며 라이센스를 지킬 수 있으신가요?
네

가위(디코접음)#8844 는 본계이고 gawi#9537는 부계입니다.

**Comment by samsunghappytree123** [comment]
✔️ 감사합니다!
