### ISSUE TITLE
[버그]

### ISSUE THREAD

**Issue by geuntae021** [samsunghappytree123/makead#13]
## 어떤 버그인가요?
지정된 카테고리에 글이 안 올라 가지는 상황

## 개발 환경은 어떠신가요?
3.8.7

**Comment by samsunghappytree123** [comment]
더 자세하게 설명해주세요.
한문장으로 처리할 수 없습니다.

**Comment by geuntae021** [comment]
> 더 자세하게 설명해주세요.
> 한문장으로 처리할 수 없습니다.

현재 봇에게 등록 커맨드를 써도 계속 올라가지지 않고 있습니다.

**Comment by geuntae021** [comment]
지금 답한지 11일이 지났는데 왜 답장이 없으신지요??

**Comment by samsunghappytree123** [comment]
NAB, 어떤 식으로 테스트해봐도 어떤 오류인지, 상세하게 말씀해주시지 않아 답변을 할 수 업습니다.

+ [``이슈 템플릿``](https://github.com/samsunghappytree123/makead/blob/master/.github/ISSUE_TEMPLATE/bug.md)을 업데이트하였습니다. 오류가 해결되지 않으면 다시 올려주세요.
