### ISSUE TITLE
[버그]

### ISSUE THREAD

**Issue by fsarewfdfwe** [samsunghappytree123/makead#14]
## 어떤 버그인가요?
> 오류 내용을 상세하게 설명해주세요.

## 개발 환경은 어떠신가요?
> 예시 : python ``3.9.6`` / discord.py ``1.7.3``

## 오류 코드가 무엇인가요?
> 오류 코드를 상세하게 설명해주세요.

Ignoring exception in on_message
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 420, in on_message
    splits = a.spilts(" ")
AttributeError: 'TextChannel' object has no attribute 'spilts'

269에 오류가 납니다!!
## 구글링을 해보셨나요?
+ [Y] 네 구글링 해보았습니다.

**Comment by samsunghappytree123** [comment]
```py
splits = a.topic.split(" ")
```

[269번째 줄](https://github.com/samsunghappytree123/makead/blob/5d5f2411ce861b80ea38c9e8496f17c12929d73f/index.py#L269)에는 정확하게 잘 나왔습니다.
해당 부분의 코드 첨부 가능할까요?

**Comment by fsarewfdfwe** [comment]
> ```python
> splits = a.topic.split(" ")
> ```
> 
> [269번째 줄](https://github.com/samsunghappytree123/makead/blob/5d5f2411ce861b80ea38c9e8496f17c12929d73f/index.py#L269)에는 정확하게 잘 나왔습니다.
> 해당 부분의 코드 첨부 가능할까요?

**Comment by fsarewfdfwe** [comment]
코드는 똑같습니다

**Comment by samsunghappytree123** [comment]
혹시 코드만 실행하시면 어떤 결과가 나오나요?
그냥 이 오픈소스의 코드로"만"요.

**Comment by fsarewfdfwe** [comment]
그냥 등록중이라고 뜨고 완료되었습니다 라고 말이 안 나와요

**Comment by samsunghappytree123** [comment]
try, except문을 주석처리하시고 오류 확인해보세요.
그 증상만 말씀해주시면, 저는 처리하고 싶지 않습니다.
