### ISSUE TITLE
[버그]

### ISSUE THREAD

**Issue by fsarewfdfwe** [samsunghappytree123/makead#15]
다시 문의드립니다.... 
제가 실수로 문제를 닫아서 다시 생성하고 올리겠습니다

코드는 똑같습니다
단지 저 부분에서
splits = a.topic.split(" ")
부분만 오류가 뜹니다
프린트 명령어를 사용하면서까지 오류를 찾은 결과였습니다

등록 명령어를 하더라고 갱신이 안됩니다

**Comment by samsunghappytree123** [comment]
#14 다시 열어드렸으니 해당 이슈에서 다시 답변드리겠습니다.
