### ISSUE TITLE
[오픈소스 사용]

### ISSUE THREAD

**Issue by jaewoolee82** [samsunghappytree123/makead#16]
## 디스코드 정보를 기재해주세요.
+ 디스코드 닉네임#태그 (Discord#0000) : 주식마스터#9580
+ 디스코드 ID (123456789) : 791881249102364692

## 오픈소스를 사용하며 라이센스를 지킬 수 있으신가요?

네

**Comment by samsunghappytree123** [comment]
✅ 확인하였습니다. 감사합니다!
