### ISSUE TITLE
[오픈소스 사용]

### ISSUE THREAD

**Issue by siren1112** [samsunghappytree123/makead#18]
## 디스코드 정보를 기재해주세요.
+ 디스코드 닉네임#태그 (신핏#1004) : 
+ 디스코드 ID (123456789) :  869568850063155292

## 오픈소스를 사용하며 라이센스를 지킬 수 있으신가요?

오픈소스 쓰면서 잘 지킬 수있습니다

**Comment by samsunghappytree123** [comment]
✅
