### ISSUE TITLE
[오픈소스 사용]

### ISSUE THREAD

**Issue by Jeongheegenius** [samsunghappytree123/makead#19]
## 디스코드 정보를 기재해주세요.
+ 디스코드 닉네임#태그 (Discord#0000) : 정희인데 _#1063
+ 디스코드 ID (123456789) : 673471748599054336

## 오픈소스를 사용하며 라이센스를 지킬 수 있으신가요?
 네!

**Comment by samsunghappytree123** [comment]
✅
