### ISSUE TITLE
[버그]

### ISSUE THREAD

**Issue by Bliss944** [samsunghappytree123/makead#2]
## 어떤 버그인가요?
채널생성이 안됩니다.
## 개발 환경은 어떠신가요?
![image](https://user-images.githubusercontent.com/73572784/104875059-ba920e80-5997-11eb-94f5-8fdd4f0a8906.png)

**Comment by samsunghappytree123** [comment]
``config.json``을 수정하셨나요?

**Comment by Bliss944** [comment]
> `config.json`을 수정하셨나요?

네

**Comment by samsunghappytree123** [comment]
어떤식으로 수정하였나요

**Comment by Bliss944** [comment]
> 어떤식으로 수정하였나요

![image](https://user-images.githubusercontent.com/73572784/104875697-46f10100-5999-11eb-8ff2-1918093cc711.png)

**Comment by samsunghappytree123** [comment]
target_category가 None인 것 같습니다. 한번 확인해보세요

**Comment by Bliss944** [comment]
> target_category가 None인 것 같습니다. 한번 확인해보세요

어디를 확인하면 되나요?
