### ISSUE TITLE
[버그]

### ISSUE THREAD

**Issue by Bliss944** [samsunghappytree123/makead#3]
## 어떤 버그인가요?
초대장 문제
## 개발 환경은 어떠신가요?
![image](https://user-images.githubusercontent.com/73572784/104884479-c4247200-59a9-11eb-9e55-295cf8a5c72a.png)

**Comment by samsunghappytree123** [comment]
버그가 아닙니다.
아마 그 서버 주인이 저일껀데 제가 초대를 삭제해서 그럽니다.
