### ISSUE TITLE
[오픈소스 사용]

### ISSUE THREAD

**Issue by kms0219kms** [samsunghappytree123/makead#4]
## 디스코드 정보를 기재해주세요.
+ 디스코드 닉네임#태그 (Discord#0000) : ! All PGS ✅#6314
+ 디스코드 ID (123456789) : 673776952578146315

## 오픈소스를 사용하며 라이센스를 지킬 수 있으신가요?
네

- 메잌애드 봇 개발 업무를 인수 받았습니다.

**Comment by samsunghappytree123** [comment]
라이센스를 지켜주셔서 감사합니다!
귀하의 봇의 번영을 기원합니다.
