### ISSUE TITLE
[오픈소스 사용]

### ISSUE THREAD

**Issue by geuntae021** [samsunghappytree123/makead#6]
## 디스코드 정보를 기재해주세요.
+ 디스코드 닉네임#태그 (DISCORD#0000) : 서준#8053- 
+ 디스코드 ID (123456789) : 698439023768764426

## 오픈소스를 사용하며 라이센스를 지킬 수 있으신가요?
<1-- ``네`` 또는 ``아니오``로 입력해주세요. --> 네. 

현재 여러개 만들떄 사용할게요!

**Comment by samsunghappytree123** [comment]
확인되었습니다.
