### ISSUE TITLE
[오픈소스 사용] Kimbab Promotional 사용 공지

### ISSUE THREAD

**Issue by MadeGOD** [samsunghappytree123/makead#7]
## 디스코드 정보를 기재해주세요.
+ 디스코드 닉네임#태그 (Discord#0000) : !안꿀꿀!
#3704
+ 디스코드 ID (123456789) : 552103947662524416

## 오픈소스를 사용하며 라이센스를 지킬 수 있으신가요?
네
<1-- ``네`` 또는 ``아니오``로 입력해주세요. -->

**Comment by samsunghappytree123** [comment]
✔ 확인하였습니다!

다른 질문 있으시면 새로운 이슈로 생성해주세요~
