### ISSUE TITLE
[오픈소스 사용]

### ISSUE THREAD

**Issue by fsarewfdfwe** [samsunghappytree123/makead#9]
## 디스코드 정보를 기재해주세요.
+ 디스코드 닉네임#태그 (Discord#0000) : 💮°£맑은달 달빛아래ᶤ ᶫᵒᵛᵉᵧₒᵤ#2854
+ 디스코드 ID (123456789) : 831150845043015724

## 오픈소스를 사용하며 라이센스를 지킬 수 있으신가요?
<1-- ``네`` 또는 ``아니오``로 입력해주세요. -->

 네

**Comment by Discord-Z** [comment]
어느서버에서 사용하실건가요?

**Comment by samsunghappytree123** [comment]
✔️ 승인되었습니다.
다음부터는 **__라이센스를 꼭 지켜주시길 바랍니다.__**

+ 다른 질문은 이슈로 생성해주세요.
